### ISSUE TITLE
Strings are sometimes not translated if source string has non-ASCII characters

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#103]
If the source (=English) string has some non-ASCII character, like “é” in “Pétanque”, the string might not be translated properly and/or there is a replacement character visible instead.

Some examples:

* Level title “Pétanque” in the level list
* Third page of post-it note in Magic Steel (contains the m-dash (“—”)
* Item name (e.g. in toolbox): “Pétanque ball”, as seen in In the Attic (for example)

Tested under: f44670d382f2159f7f210d53c3000d7c2afd3280

**Comment by kaa-ching** [comment]
Confirmed, I see a <?> character in "in the attic" in German.
