### ISSUE TITLE
QDialogs works bad with ui

### ISSUE THREAD

**Issue by glixx** [kaa-ching/tbe#12]
Steps to reproduce:
- tbe
- File->Open level (Save, Save as...  are the same)
- title of main window was lost, descripton was lost, etc. - everythink is like default ui.

There is screenshot with problem.
![tbe1](https://cloud.githubusercontent.com/assets/2681872/9157010/71f4ba5a-3ef5-11e5-9acf-cdf9fa5a1e52.png)

**Comment by glixx** [comment]
I think how to fix:
add new procedure before call QDialog, which will hide window and save current strings.
add new procedure after call QDialog, which will show window and restore current strings.

**Comment by kaa-ching** [comment]
Confirmed. Actually this looks like it only happens on the first try.
If you actually open a level and then again open a level, it doesn't get emptied anymore.

**Comment by glixx** [comment]
> Actually this looks like it only happens on the first try.

No. I see translation for button "Reset" for Russian from qt, not from tbe in this case. So problem is deeper.

**Comment by kaa-ching** [comment]
moving to milestone B as that option no longer is in the menu.

**Comment by kaa-ching** [comment]
I would not be surprised if this is a side effect of issue #30...

**Comment by kaa-ching** [comment]
I don't see this issue anymore.
