### ISSUE TITLE
Add static wedges

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#124]
I noticed you recently made wedges movable (again?).
So the wedges are not static objects anymore.
This change hit me badly because I was recently working on a really complex level (still WIP) which heavily relied on wedges being static, and most of them would go into the toolbox. It's a level where I don't want have too much movable objects in a toolbox, or it might become too easy. And I also can't easily transform the wedges into ramps, they should be wedges (also for aesthetic reasons).

So yeah, this is a request for adding static wedges along with the (now) movable ones. The static wedges get the oldwood texture like Floor and QuarterArc40. So there would be 2 kinds of wedges, a distinction like we have now with Floor and BirchBar. What about calling the movable wedges “birch wedges” or something? xD But how to call the static wedges? Hmmm, I don't know. :-(

For my recent level “Maze”, I also relied on wedges being static, but for Maze it's no big deal you changed them to ramps, the level still is basically the same.

**Comment by kaa-ching** [comment]
we also have ramps ;-)

**Comment by Wuzzy2** [comment]
Right, but they are not the same because of the triangle shape. Having static wedge would be really convenient.

Just to make it clear: Don't you want to add them? Because if not, I will just hack my way around it.

**Comment by kaa-ching** [comment]
I don't mind having them. Go ahead, submit a patch adding oldwood wedges - the imagery is present anyway, right?

**Comment by kaa-ching** [comment]
Apparently the images weren't present. Thanks for the fix!
