### ISSUE TITLE
“Resizable” property does not work for some objects

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#127]
It seems the property “Resizable” has no effect on objects other than RectObjects. It works for stuff like Floor or Wall.
But you can't put things like resizable wedges into the toolbox, for example.

f0cf4173f68199263d393ff9a3f5bfd54a040b1d

**Comment by kaa-ching** [comment]
I made *every* object now able to listen to resizing. 
However, it doesn't make sense to resize a Cola bottle, for example. 
Don't slap it on random objects, please :wink:

There's another issue to be aware of: if the area of the object gets too small, e.g. with a Ramp that is only a few mm wide and 20cm high, the physics engine will go bonkers.
