### ISSUE TITLE
Explosions do not pop balloons

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#130]
Seen in c1e3af453fc129d4f132e6b30aa951ad4cf8dfb3.

If you detonate dynamite near or directly next to a ballon, the balloon does not pop. The ballon is pushed around pretty hard, but it does not pop.

I don't know if this is intentional or just an oversight.

**Comment by kaa-ching** [comment]
I can fix this easily if we going to say that explosions always pop a balloon, even if the balloon is very far away...

**Comment by Wuzzy2** [comment]
Do you mean with “explosion” these small cola-spray-like particles? In that case, that would be not really nice as well, I think.
Hmmmm …

**Comment by kaa-ching** [comment]
The force of the explosion is modeled using a particle mechanism. The ExplosionSplatter is indeed a particle, but it's different from the ColaSplatter. 
I can give ExplosingSplatter popping capabilities without giving the ColaSplatter popping capabilities.

My question is whether an ExplosionSplatter should *always* cause a balloon to pop.

**Comment by Wuzzy2** [comment]
No, I don't think it is right to pop ballons by any explosion particle.

Maybe you could check the particle speed and its travelled distance.
If the particle is going fast and did not travel far yet, it makes ballon go pop.
But if the particle is going (relatively) slow and is travelled a large distance (or is nearly at the end of its “life time” (if is has something like that)), it won't make ballons go pop.

On the other hand, its a bit weird how the explosion works, in my opinion. Its hardly predictable where the particles are going. Plus, they tend to bounce around a lot. A slight change in dynamite position can change the particle “ways” dramatically. This can have nastiy side effects like randomly pushing far objects around by pure luck. Not only balloons.
Maybe this is why you have difficulties in getting Zoing and Boom right.

What do you think?
