### ISSUE TITLE
Incorrect fsf address

### ISSUE THREAD

**Issue by glixx** [kaa-ching/tbe#15]
fsf address was changed. This is rpmlint check (but it searches not all, needs manually check also):

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/AbstractObject.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/GoalEditor.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ViewWorld.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/AbstractObject.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/TranslationGuide.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/BalloonCactus.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/AbstractJoint.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/Property.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/TriggerExplosion.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/WinFailDialog.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/TranslationGuide.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/ChoosePhoneUndoCommand.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/MainWindow.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/Butterfly.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/CircleObjects.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/PivotPointPtr.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/animateddialog.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/RectObject.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/Scenery.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/Link.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ChoosePhoneNumber.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/MoveUndoCommand.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/Spring.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/resizinggraphicsview.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ViewLink.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/ColaMintBottle.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/loadsave/GoalSerializer.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/MoveUndoCommand.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/UndoSingleton.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/Link.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/loadsave/ToolboxGroupSerializer.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ToolboxListWidgetItem.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/loadsave/LocalString.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/UndoSingleton.h
                                                                                                                                           
tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ChooseLevel.h                                      
                                                                                                                                           
tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/RectObject.cpp                                    

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/loadsave/AbstractObjectSerializer.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/PostIt.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/ColaMintBottle.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/PieMenu.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/Glue.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/PolyObject.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/loadsave/Level.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ImageCache.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/World.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ImageCache.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/SaveLevelInfo.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/DummyUndoCommand.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/loadsave/ObjectFactory.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/Glue.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/DeleteUndoCommand.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/PieMenu.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/ViewObjectActionDectorator.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/TriggerExplosion.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/loadsave/ToolboxGroupSerializer.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/loadsave/BackgroundSerializer.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ViewDetonatorBox.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/Position.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/GameResources.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/Spring.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/AbstractUndoCommand.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ListViewItemTooltip.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/RotateUndoCommand.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/main.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/Goal.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/EditObjectDialog.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ViewDetonatorBox.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/Scenery.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/animateddialog.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/PolyObject.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ToolboxListWidgetItem.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ViewObject.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/AbstractObjectPtr.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/ToolboxGroup.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ChoosePhoneNumber.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/RotateUndoCommand.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/CircleObjects.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/BalloonCactus.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/tbe_global.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/PivotPoint.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/loadsave/ObjectFactory.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/AbstractJoint.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/EditLevelProperties.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ViewLink.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/PostIt.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/Goal.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/EditObjectDialog.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/loadsave/AbstractObjectSerializer.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/InsertUndoCommand.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ChooseLevel.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/Background.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/SimulationControls.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/DeleteUndoCommand.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/ResizeUndoCommand.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/GoalEditor.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/ViewObjectActionDectorator.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ViewObject.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/loadsave/LocalString.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/SimulationControls.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/WinFailDialog.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/GameResources.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/World.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ViewWorld.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/loadsave/Level.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/Position.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/resizinggraphicsview.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/InsertUndoCommand.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/AbstractUndoCommand.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/loadsave/GoalSerializer.h
                                                                                                                                           
tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/ToolboxGroup.cpp                                

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/Butterfly.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/DummyUndoCommand.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/ChoosePhoneUndoCommand.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/backtrace.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/control/ResizeUndoCommand.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/Property.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/TranslationGuidePtr.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ViewPostIt.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/loadsave/BackgroundSerializer.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/SaveLevelInfo.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/Popup.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/model/PivotPoint.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/EditLevelProperties.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/MainWindow.cpp

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ViewPostIt.h

tbe-debuginfo.i586: W: incorrect-fsf-address /usr/src/debug/tbe-0.9-git9fafd72/src/view/ListViewItemTooltip.cpp

**Comment by kaa-ching** [comment]
Looks like a simple search-and-replace issue.

**Comment by kaa-ching** [comment]
New address is:

Free Software Foundation
51 Franklin Street, Fifth Floor
Boston, MA 02110-1335
USA
