### ISSUE TITLE
Do not install levels/test

### ISSUE THREAD

**Issue by glixx** [kaa-ching/tbe#16]
Directory levels/test is OK to keep in sources, but don't install.

**Comment by kaa-ching** [comment]
Agreed. Need to change
CMakeFiles.txt in the top level, adjust:

install(DIRECTORY levels 
	DESTINATION .
	PATTERN ".svn" EXCLUDE
)

to also exclude the test directory.

**Comment by kaa-ching** [comment]
Fixed by commit f086592814a016fc1315ab27863fc20dd220c0ec .
