### ISSUE TITLE
Icon with better quality

### ISSUE THREAD

**Issue by glixx** [kaa-ching/tbe#17]
CMakeLists.txt: install(FILES imagery/illustrations/tbe-icon.png DESTINATION images RENAME TheButterflyEffect-icon.png)
1) You install imagery/illustrations/tbe-icon.png, but imagery/illustrations/tbe-icon.ico is with better quality.

2) With imagemagick for packages:
mkdir -p installer/icons/hicolor/{128x128,64x64,48x48,32x32,16x16}/apps
convert -scale 16x16 imagery/illustrations/tbe-icon.ico installer/icons/hicolor/16x16/apps/tbe.png
convert -scale 32x32 imagery/illustrations/tbe-icon.ico installer/icons/hicolor/32x32/apps/tbe.png
convert -scale 48x48 imagery/illustrations/tbe-icon.ico installer/icons/hicolor/48x48/apps/tbe.png
convert -scale 64x64 imagery/illustrations/tbe-icon.ico installer/icons/hicolor/64x64/apps/tbe.png
convert -scale 128x128 imagery/illustrations/tbe-icon.ico installer/icons/hicolor/128x128/apps/tbe.png
So, I'll copy installer/icons/* into /usr/share/icons for tbe package.

**Comment by kaa-ching** [comment]
please provide a patch.

**Comment by glixx** [comment]
For your installer:
install(FILES imagery/illustrations/tbe-icon.ico DESTINATION images RENAME TheButterflyEffect-icon.ico)
Icon=%TBE%/images/TheButterflyEffect-icon.ico

For package:
run commands, which was written in the first message.

**Comment by kaa-ching** [comment]
I've done 50%. I don't understand the other part. Apparently you're talking about multiple files.
Oh well, maybe I'm just too tired...

**Comment by glixx** [comment]
```diff
- install(FILES imagery/illustrations/tbe-icon.png DESTINATION images RENAME TheButterflyEffect-icon.png)
+ install(FILES imagery/illustrations/tbe-icon.ico DESTINATION images RENAME TheButterflyEffect-icon.ico)
```
```diff
- Icon=%TBE%/images/TheButterflyEffect-icon.png
+ Icon=%TBE%/images/TheButterflyEffect-icon.ico
```
