### ISSUE TITLE
Remove references to sourceforge everywhere

### ISSUE THREAD

**Issue by kaa-ching** [kaa-ching/tbe#19]
CMakeLists.txt: install(FILES installer/sourceforge.net-tbe.desktop DESTINATION .
installer/uninstall_icons.sh:ICON=sourceforge.net-tbe.desktop
installer/tbe.spec:URL:            https://sourceforge.net/projects/tbe
installer/install_icons.sh:ICON=sourceforge.net-tbe.desktop
INSTALLING:https://sourceforge.net/apps/trac/tbe/wiki/HowToMakeARelease
src/view/MainWindow.cpp:                                   "http://sourceforge.net/projects/tbe/forums/forum/953128\">"
src/view/MainWindow.cpp:                                   "http://sourceforge.net/projects/tbe/forums/forum/953128</a>"
src/model/TranslationGuide.h:/// See also http://sourceforge.net/apps/trac/tbe/wiki/TranslationGuide
src/model/PivotPoint.h:/// See also http://sourceforge.net/apps/trac/tbe/wiki/PivotPoint

**Comment by kaa-ching** [comment]
sourceforge is also mentioned in the translations - most of them will go away after updating the translations. However, we still have to move the forums...

**Comment by glixx** [comment]
Better to use tbe.desktop only. If you want to change paths, then for install_icons.sh, uninstall_icons.sh:
sed -i "s|Exec=.*|Exec=path/tbe|g" tbe.desktop
sed -i "s|Icon=.*|Icon=path/tbe.png|g" tbe.desktop
sed "/Icon\[.*\]=/d" tbe.desktop
So, sourceforge.net-tbe.desktop is deprecated.
Extension for icon should be used if only "path" present. Standard to have name for icon and for program the same.

Transifex.com is for translations: https://www.transifex.com/Magic/thebutterflyeffect/ . Translators don't need special instructions, wiki.

Site http://the-butterfly-effect.org/ is redirect on https://sourceforge.net/projects/tbe/ now.

**Comment by glixx** [comment]
Needs redirect from https://sourceforge.net/projects/tbe/ to here or other info about new github.

**Comment by kaa-ching** [comment]
Yup, did that. Also removed the 'wikis' from sf and set 'support' to point to the github issue tracker.

**Comment by glixx** [comment]
SF allows redirect: Admin->Metadata->Project Status:->Edit->Moved Project to:

**Comment by kaa-ching** [comment]
glixx wrote: `SF allows redirect: Admin->Metadata->Project Status:->Edit->Moved Project to:`

Indeed, but that adds a blue line "this project has moved to" at the top of the page. The rest remains as-is. 
I think I do want to keep sourceforge around, as I need some location to store the tarballs/packages/installers - github only cares about source code.
So I disabled that one again.

**Comment by kaa-ching** [comment]
There are no references left. yay!

**Comment by glixx** [comment]
> I think I do want to keep sourceforge around, as I need some location to store the tarballs/packages/installers - github only cares about source code.

No. Please look at example:
http://viktor-zin.github.io/afce/
https://github.com/viktor-zin/afce/tree/gh-pages

You are able to create web-site and to store all tarballs/packages/installers.

**Comment by kaa-ching** [comment]
Indeed, the tarballs are on the github.io page - i.e. the 'gh-pages'.
No clue how to use that and I don't have a lot of time.
But creating a single front page and totally get rid of sourceforge looks appealing.

**Comment by glixx** [comment]
```diff
grep -r "the-butterfly-effect.org"        
levels/angry/stick-figure-attack.svg:            <dc:title>the-butterfly-effect.org</dc:title>
levels/angry/stick-figure-shoot.svg:            <dc:title>the-butterfly-effect.org</dc:title>
DESCRIPTION:   http://www.the-butterfly-effect.org/
README.md:go to          http://the-butterfly-effect.org/
README.md:   http://www.the-butterfly-effect.org/
src/main.cpp:   QCoreApplication::setOrganizationName("the-butterfly-effect.org");
src/main.cpp:   QCoreApplication::setOrganizationDomain("the-butterfly-effect.org");
CMakeLists.txt:SET(CPACK_PACKAGE_VENDOR "www.the-butterfly-effect.org")
CMakeLists.txt: SET(CPACK_NSIS_HELP_LINK "http:\\\\\\\\www.the-butterfly-effect.org")
CMakeLists.txt: SET(CPACK_NSIS_URL_INFO_ABOUT "http:\\\\\\\\www.the-butterfly-effect.org")
CMakeLists.txt: SET(CPACK_NSIS_CONTACT "info@the-butterfly-effect.org")
CMakeLists.txt: SET(CPACK_PACKAGE_CONTACT "info@the-butterfly-effect.org")
imagery/src/Glue/GlueBlob.svg:            <dc:title>the-butterfly-effect.org</dc:title>
imagery/src/Balls/PetanqueBoule.svg:            <dc:title>the-butterfly-effect.org</dc:title>
imagery/src/TriggerExplosion/DetonatorBoxActivated.svg:            <dc:title>the-butterfly-effect.org</dc:title>
imagery/src/TriggerExplosion/DetonatorBoxHandle.svg:            <dc:title>the-butterfly-effect.org</dc:title>
imagery/src/TriggerExplosion/DetonatorBox.svg:            <dc:title>the-butterfly-effect.org</dc:title>
imagery/src/TriggerExplosion/DynamiteActive.svg:            <dc:title>the-butterfly-effect.org</dc:title>
imagery/src/TriggerExplosion/Dynamite.svg:            <dc:title>the-butterfly-effect.org</dc:title>
imagery/src/TriggerExplosion/DynamiteBoom.svg:            <dc:title>the-butterfly-effect.org</dc:title>
imagery/src/TriggerExplosion/DetonatorBoxRinging.svg:            <dc:title>the-butterfly-effect.org</dc:title>
imagery/src/TriggerExplosion/DynamiteRinging.svg:            <dc:title>the-butterfly-effect.org</dc:title>
imagery/src/TriggerExplosion/DetonatorBoxDone.svg:            <dc:title>the-butterfly-effect.org</dc:title>
imagery/src/RectObjects/spring20.svg:            <dc:title>http://the-butterfly-effect.org/</dc:title>
```
Site http://the-butterfly-effect.org/ is redirect on https://sourceforge.net/projects/tbe/ now.
So there are references on SF still.

**Comment by DjSlash** [comment]
> as I need some location to store the tarballs/packages/installers - github only cares about source code.

Actually, you can easily [create releases](https://help.github.com/articles/creating-releases/) by using [tags](https://help.github.com/articles/about-releases/). :)

**Comment by kaa-ching** [comment]
@DjSlash : it's not about tagging releases, it's about storing the binary installers, deb and rpm files.

Would you by any chance be interested to craft the new front page?

**Comment by DjSlash** [comment]
There is still a possibility to add binary files to a release:
> If you'd like to include binary files along with your release, such as compiled programs, drag and drop or select files manually in the binaries box. 

[Random example](https://github.com/atom/atom/releases)

And yes, I wouldn't mind setting up a page. When I find time, at least after next weekend.

**Comment by glixx** [comment]
Web page with screenshots is ideal solution.

**Comment by kaa-ching** [comment]
I've updated the gh-pages big time: there's a lot more contents now.
Probably not all of that should remain in the front page - however, it appears to be 'modern' to have one huge scrollable page again... I'm feeling like it's the late 90s again, but ok...

Anyway: that page is a mess - most of it doesn't display correctly. Probably needs some more configuration tweaking. I hope that @DjSlash can help here :wink:

**Comment by kaa-ching** [comment]
BTW: @glixx: the transifex page still points to the SF site :stuck_out_tongue:

**Comment by DjSlash** [comment]
hmm, i definitly see some improvements :stuck_out_tongue_winking_eye: No worries, I'll look into that. I'll tinker things every now and then, keep you updated.

My own preference is also to make seperate pages for a few things. Like the installation instructions and maybe use the open source part as an introduction to a page about helping out and the projects used? 

BTW, I've created a issue label for the website, so anything related to that can be labeled as such.

**Comment by glixx** [comment]
I updated URL for TX to http://kaa-ching.github.io/tbe

**Comment by kaa-ching** [comment]
Apart from fixing the website (issue #37) and switching the meta  part of sourceforge, I hope we're ready to go!

**Comment by kaa-ching** [comment]
Actually not, there's a few references in the sourcecode left:
```
src/model/PivotPoint.h:/// See also http://sourceforge.net/apps/trac/tbe/wiki/PivotPoint
src/model/TranslationGuide.h:/// See also http://sourceforge.net/apps/trac/tbe/wiki/TranslationGuide
src/view/MainWindow.cpp:  "http://sourceforge.net/projects/tbe/forums/forum/953128\">"
src/view/MainWindow.cpp:  "http://sourceforge.net/projects/tbe/forums/forum/953128</a>"
```

**Comment by kaa-ching** [comment]
Too bad that now all translations lag behind. I'm going to release!

**Comment by glixx** [comment]
And to touch translations before release?
https://github.com/kaa-ching/tbe/commit/b9a1b2f4c839ef0c247ee302040517985c24f550

**Comment by glixx** [comment]
Site http://the-butterfly-effect.org/ is redirect on https://sourceforge.net/projects/tbe/ now.

**Comment by kaa-ching** [comment]
Yes, will ask the webmaster to fix that tomorrow.
