### ISSUE TITLE
Tooltips problems

### ISSUE THREAD

**Issue by glixx** [kaa-ching/tbe#21]
Incorrect tooltips:
picnic/picnic-0.xml: from Domino
games/supertuxkart.xml: from Cola
angry/birds2.xml: from Wedge
elce09/006.xml: from BowlingBall

Description key did not show as tooltip:
jumpingjack/party-at-office.xml

Any CustomBall needs own tooltips:
draft/cola-powered-bike.v2.xml for wheel
draft/steam-machine.xml for wheel
draft/poing-poing-poing.xml
draft/zoingandboom.xml for wheels
draft/contraption2.xml
draft/float-balloon-float.xml
draft/factory.xml for wheel

Tolltip for "Send BOOM to %1" does not update after enter phone number.

**Comment by glixx** [comment]
"CustomBall" was not mark for translation.

**Comment by kaa-ching** [comment]
> "CustomBall" was not marked for translation.

Indeed, as it is not supposed to be used by itself, but also mandate a Description and Name change.
Would it help if the code checks for that (in debug versions only)?

**Comment by glixx** [comment]
To add Description key for context where CustomBall was used: wheel, ball, center of mass, etc. and use Description as tooltip for CustomBall. For release version too.

**Comment by kaa-ching** [comment]
commit 6f9ca48 belongs here

**Comment by kaa-ching** [comment]
All "Incorrect tooltips:" are verified done.

**Comment by kaa-ching** [comment]
CustomBall no longer has a default tooltip - that solves most of the other entries.

**Comment by kaa-ching** [comment]
Still to do:  `Tooltip for "Send BOOM to %1" does not update after enter phone number.`

**Comment by kaa-ching** [comment]
all done now. closing.
