### ISSUE TITLE
Wrong encoding for non-latin

### ISSUE THREAD

**Issue by glixx** [kaa-ching/tbe#22]
LC_ALL=C tbe
![tbe4](https://cloud.githubusercontent.com/assets/2681872/9388536/c169165e-476e-11e5-918b-ecf857b48b5d.png)

**Comment by kaa-ching** [comment]
That commit didn't help.
I'm not sure what to do about this. 

If you set LC to C, AFAIK there's no UTF-8. So UTF-8 in strings is interpreted as plain ASCII, which is what we see here.

In that case: whose fault is this? And what can we do about it?

**Comment by kaa-ching** [comment]
I think I found it:
from page https://forum.qt.io/topic/4337/convert-qstring-into-qbytearray-as-either-utf-8-or-latin1/6 :
`setCodecForLocale and setCodecForCStrings only affect the construction of QStrings.`

At the time I set the Locale and CStrings for input to UTF-8 (i.e. within main()), the strings we're looking at are already set - they are set prior to entering main().

**Comment by kaa-ching** [comment]
it took a while to figure out what the solution was - it's actually nicely supported in Qt if done right.
