### ISSUE TITLE
Missing Description/tooltip

### ISSUE THREAD

**Issue by glixx** [kaa-ching/tbe#23]
For toolboxitem:
* [x] picnic/picnic-1.xml for "Wooden Beam"
* [x] draft/turn-it-around.xml for "Hammer"
* [x] draft/bridge_gap.xml for "Beam"
* [x] draft/balloons-go-up.xml for "Floor"
* [x] draft/pinrack.xml for "Wooden bar"
* [x] draft/styrofoam.xml for "Styrofoam Block"
* [x] jumpingjack/party-at-office.xml for "Floor"
* [x] draft/poing-poing-poing.xml for "Something weird"
* [x] elce09/005.xml for "Boulder"
* [x] elce09/005.xml for "Styrofoam"
* [x] draft/spare-the-balloon.xml for "Wooden bar"
* [x] draft/bridge-2.xml for "Beam"
* [x] draft/bridge-3.xml for "Beam"
* [x] draft/bridge-3.xml for "Hammer"
* [x] picnic/picnic-3.xml for "Stop"
* [x] draft/domino_day.xml for "Block"
* [x] draft/geyser.xml for "Beam"
* [x] elce09/006.xml for "Cola Crate"
* [x] elce09/006.xml for "Wooden bar"
* [x] draft/loopings2.xml for "Block"
* [x] elce09/007.xml for "Styrofoam"

But if to add Description key in these files, then such objects will not have tooltips in another levels.

**Comment by kaa-ching** [comment]
Fixed a few of them, just for fun.

**Comment by kaa-ching** [comment]
almost done!

**Comment by kaa-ching** [comment]
completely done!
