### ISSUE TITLE
build correct installation tree

### ISSUE THREAD

**Issue by kaa-ching** [kaa-ching/tbe#24]
As suggested by glixx and others, the install tree for tbe is wrong.
Please fix to make packaging easier.

**Comment by kaa-ching** [comment]
TODO:
 * icons
 * desktop file

**Comment by kaa-ching** [comment]
Note that I don't want to hard code absolute paths into the binary because that will break local development, regression testing and Windows.
I think with the current solution, I don't need to - it should work everywhere.

**Comment by kaa-ching** [comment]
Whoops, the 'make package' target also doesn't work anymore.

**Comment by glixx** [comment]
Installation for docs: to enable by default, but needs option to disable while installing.

**Comment by kaa-ching** [comment]
glixx wrote: `Installation for docs: to enable by default, but needs option to disable while installing.`

My goal is to build a single RPM or DEB, TGZ or installer that contains all - including documentation. These will be uploaded to sf.net or github for people who want to play TBE on distros that do not supply TBE in their repos (i.e. all but Mageia).

I presume that your spec file for Mageia splits the build tree into several RPM packages and packages for Mageia. Thus I won't distinguish between docs or anything: your spec file will. Or am I wrong?

**Comment by glixx** [comment]
RPM distros uses %doc macros (see spec file) for docs installation (they can have different paths for docs installation, but /usr/share/doc is often). So I need option to disable installation for docs and use %doc instead. Now installation for docs is twice.

**Comment by kaa-ching** [comment]
Done.
