### ISSUE TITLE
Finish new listviewtooltip dialog

### ISSUE THREAD

**Issue by kaa-ching** [kaa-ching/tbe#3]
it needs more polish: put background images to make it look like a text balloon

it also should show clearly that you want to push on an object, not drag it.
Or, we should enable drag&drop - which is complex code to add.

**Comment by kaa-ching** [comment]
I'm moderately happy with the changes:

* background has image
* all text is visible
* image is set to the right size

I'm not really happy:

* total dialog is not correctly scaled (reduction, usually)
* the close button still needs different icon.

**Comment by glixx** [comment]
Fix cutted description for BowlingPin:
```diff
diff -ur tbe-0.9-git0de2b0f.orig/src/model/PolyObject.cpp tbe-0.9-git0de2b0f/src/model/PolyObject.cpp
--- tbe-0.9-git0de2b0f.orig/src/model/PolyObject.cpp	2015-08-20 18:49:20.000000000 +0300
+++ tbe-0.9-git0de2b0f/src/model/PolyObject.cpp	2015-08-20 23:17:50.000000000 +0300
@@ -46,7 +46,7 @@
 	"BowlingPin",
 	QT_TRANSLATE_NOOP("AbstractPolyObjectFactory", "Bowling Pin"),
 	QT_TRANSLATE_NOOP("AbstractPolyObjectFactory", "Bowling pins are meant to be run "
-				"over - and most people prefer to do that using "
+				"over -\nand most people prefer to do that using "
 				"a Bowling Ball."),
 	"BowlingPin",
 	"(0.02,0.17)=(-0.02,0.17)=(-0.045,0.14)=(-0.04,0.065)=(0.0,0.04)"
```

**Comment by glixx** [comment]
Pictures does not fit in window.
![tbe6](https://cloud.githubusercontent.com/assets/2681872/9395184/b28812ee-4795-11e5-9943-49154aff4f69.png)

**Comment by kaa-ching** [comment]
The last commit fixes all for me :-)
