### ISSUE TITLE
Regress with lang for descriptions

### ISSUE THREAD

**Issue by glixx** [kaa-ching/tbe#30]
Descriptions keys (tooltips) are in Dutch.
This is screenshot from Russian, but tooltip is Dutch.
![tbe0](https://cloud.githubusercontent.com/assets/2681872/9789253/9b0a4950-57d7-11e5-8b3d-2e98254b6f03.png)

**Comment by glixx** [comment]
![tbe2](https://cloud.githubusercontent.com/assets/2681872/9789934/9d67d164-57db-11e5-9091-8bebd9dd9b4b.png)

**Comment by kaa-ching** [comment]
How on earth did this happen?
Obviously I'll have to run the scripts to make the level translations work - I tend not to do that.

**Comment by glixx** [comment]
Please use Description if lang="lang" from this line. Now you use the latest line with Description.

**Comment by kaa-ching** [comment]
My head hurts!
I really don't know why this is happening :-(

**Comment by kaa-ching** [comment]
Indeed, I think you are right: the last tool tip from the Description tag is used, regardless of which language is selected. This is also clear from AbstractObject::getToolTip() - there is NO support for languages in there... My bad!

**Comment by kaa-ching** [comment]
I think the only true way to solve this, is to get rid of the property "Description" in all of the levels.
And that's a lot of editing...
So, i'll need a sed script to turn a line like:
``` 
<property key="Description">This is an egg. Rather easy to break, I'd say...</property>
<property key="Description" lang="ru">Это яйцо. Его довольно легко разбить...</property>
```

into:

``` 
<tooltip>This is an egg. Rather easy to break, I'd say...</tooltip>
<tooltip lang="ru">Это яйцо. Его довольно легко разбить...</tooltip>
```

@glixx ? @DjSlash   - any of you smart enough to write that sed script? We can fix the remaining issues by hand!

At the same time, I'll start hacking the code to disallow the Description property and make everything else work...

**Comment by kaa-ching** [comment]
Maybe editing by hand will be enough - the following levels need 'help':
```
./picnic/picnic-0.xml
./angry/birds2.xml
./angry/birds1.xml
./jumpingjack/party-at-office.xml
./draft/save-the-butterfly.xml
./games/supertuxkart.xml
./elce09/006.xml
./elce09/005.xml
./elce09/003.xml
./elce09/001.xml
./elce09/brother-plays-soccer.xml
```

**Comment by kaa-ching** [comment]
and *now* it's closed. Thanks @DjSlash for fixing the levels.
