### ISSUE TITLE
Finish the i18n strings

### ISSUE THREAD

**Issue by kaa-ching** [kaa-ching/tbe#33]
No clue how we should handle this.
How to communicate that we're in 'freeze' and only allow bugfixes and updates to i18n?

**Comment by glixx** [comment]
Transifex has announcements form to write about freeze and any other info.
![tbe3](https://cloud.githubusercontent.com/assets/2681872/9834061/d888dc3c-59b3-11e5-902d-b6ea9be25210.png)
Did you recieve test message by email from transifex?
![tbe4](https://cloud.githubusercontent.com/assets/2681872/9834064/04970ff6-59b4-11e5-8f06-b64bf7a88e15.png)
If you press "Watch project" button, then you will receive email when files (TS, POT, desktop) will be changed for translation.

**Comment by glixx** [comment]
There are opened bugs when new string will be added: https://github.com/kaa-ching/tbe/issues/9 , https://github.com/kaa-ching/tbe/issues/23

**Comment by kaa-ching** [comment]
Issue #9 is a hard one. It's the most important bug that needs squashing before release.

**Comment by kaa-ching** [comment]
After issue #30 is finished, there's new strings to translate in levels. This will also require changing the translation script.

**Comment by kaa-ching** [comment]
at this point, it appears that the translations no longer work :unamused:

**Comment by glixx** [comment]
What does not work?

**Comment by kaa-ching** [comment]
@glixx : See the Windows screenshot in issue #35.
The same happens right now on Linux: the level translations work, but the UI translations are not picked up anymore. By the way: can you get me an update of the *ts files from Transifex, please?

**Comment by kaa-ching** [comment]
Commit a569eae removes the original level translations from the levels, fixes indentation and other small XML annoyances. This leaves it to @glixx to update his script (I believe that you still need to add `tooltip` as something translatable?).

**Comment by glixx** [comment]
Hi Klaas, I'm busy this month and will look later.

**Comment by kaa-ching** [comment]
bisecting:
 * git commit 5712ae793e0ab4ba9fbc2383bb4b34b7a415f964  i18n still works
 * git commit 9fbcfd47276dbc36e23e302876c4ff96953eba9a works
 * git commit 08625625176e0a0bb05bdbace53e64ee1895ade4 doesn't
 * git commit c3cfcf5a0ea51d63c37cf5c4da5b26d44b444edd doesn't 
 * git commit ed57069ba20b9922f685c2a87156483d930c8bab doesn't

Looking at the commit messages, it's b18b580ce5cc78e922ca5b86e09a7127531ecb94 that makes things fail.

**Comment by kaa-ching** [comment]
Indeed, b18b580 is the culprit. The cause is a change in scoping of the QTranslator. Commit 1e8a5aa fixes it by adjusting the lifetime of the QTranslator. At the same time, fixing another issue: theIsRunAsRegression wasn't set to true yet when reading it...

**Comment by kaa-ching** [comment]
@glixx: I think the game is ready for milestone A, except for the latest language support (and the website). Can you please send me the latest *.ts and *.pot files? I tried to get them from Transifex myself, but I cannot find a mechanism to retrieve them :unamused:

**Comment by glixx** [comment]
No, not ready. I see regresses since 4e6fd4f6cd when I tested the latest time. Needs more work.

**Comment by kaa-ching** [comment]
you filed issue #38 and #39 for that. I will work on it.

**Comment by kaa-ching** [comment]
Git commit 8e4d2d4 finishes the language support for Milestone A. Closing this ticket.
