### ISSUE TITLE
error dialog on start unreadable

### ISSUE THREAD

**Issue by kaa-ching** [kaa-ching/tbe#36]
When following the build instructions for Windows, once you build the application and click the _Run_ button, the resulting TBE application will show _only_ the following dialog:
![error-tbe-start-cannot-find-levelsxml](https://cloud.githubusercontent.com/assets/4249656/10177818/9118cb68-66fc-11e5-9889-fd2d9ff3b9e2.png)

**Comment by kaa-ching** [comment]
Unfortunately, it's similar for Linux:
![tbe-linux-cannot-find-levelsxml](https://cloud.githubusercontent.com/assets/4249656/10177866/c8974a9c-66fc-11e5-9896-e425c983500a.png)

**Comment by kaa-ching** [comment]
NOTE: this issue is about the dark-grey-on-black, Not really about the message displayed on the dialog. But I'd prefer to fix both. At least this has nothing to do with the style sheet on MainWindow.ui, these dark colors have another source.

**Comment by kaa-ching** [comment]
![critical-error-works-now](https://cloud.githubusercontent.com/assets/4249656/10468689/ad719b46-7200-11e5-9866-db348296d532.png) it works again (?!?), both on Windows and on Linux. I don't get it :unamused:

**Comment by DjSlash** [comment]
What would trigger that dialog on LInux? Wondering if I have either result (working or not).

**Comment by kaa-ching** [comment]
@DjSlash  wrote:
`What would trigger that dialog on LInux? Wondering if I have either result (working or not).`

e.g. if you remove the levels.xml file from the installed tree.
It would be nice to binary dissect which patch caused it and which patch fixed it. Because I have no clue... But I'm not in the mood to figure it out - I'll accept it is gone happily :smile:

**Comment by DjSlash** [comment]
Heh :)

Ok, I can confirm that the dialog on my machine is also working like it supposed to. So yes, let's just accept how it is. :smile:
