### ISSUE TITLE
Installer for linux is broken

### ISSUE THREAD

**Issue by glixx** [kaa-ching/tbe#38]
make install works wrong because of PACK condition, make regression does not start because of wrong path to tbe executable.
it was OK for 4e6fd4f6cd

**Comment by kaa-ching** [comment]
This resolves the issues for Linux (if you use the top-level Makefile). It also resolves the issues for Windows if you stick to the wiki page https://github.com/kaa-ching/tbe/wiki/WindowsBuild

**Comment by kaa-ching** [comment]
The issue was already solved in my tree, but I forgot to commit it.
