### ISSUE TITLE
Website improvements

### ISSUE THREAD

**Issue by DjSlash** [kaa-ching/tbe#40]
This is an issue about improvements for the website that I'd like to do for Milestone B. This list is not put in stone, so there might be additions or removals along the way. If there's is anything you'd like to see, let me know in a comment.
- [ ] Expand the sidebar:
  - [x] Mention latest posts
  - [ ] Mention latest release version
- [ ] "Jekyllify" the screenshots:
   The screenshots-section is now somewhat hardcoded. Would like to make it easier to add new/other images.

**Comment by kaa-ching** [comment]
I'd like to make it visually more appealing, like most "modern websites", e.g. https://www.google.com/nexus/5x/ , i.e. large graphics, maybe something moving, variation in backgrounds, etc.

**Comment by DjSlash** [comment]
I agree that we could add some extra visual stuff. I could make the screenshots appear in a "[carousel](http://getbootstrap.com/javascript/#carousel)". Or we could create a GIF of a level being played. Or an background image that has elements of the game in it.

I'm not sure if your link is the best example, unless you would want to highlight every feature with big images. ;-) But I wouldn't mind to trim some of the texts (and put trimmed text elsewhere).

Take a look at the website of [Bootstrap](https://getbootstrap.com) or their [expo](http://expo.getbootstrap.com/) -- it might get you some inspiration about what can be achieved with it.

**Comment by kaa-ching** [comment]
Superfluous polish: logos in front of the various distros :smiley:

**Comment by kaa-ching** [comment]
Although the screenshots may not be Jekyll technology, they do appear correctly on mobile displays.
Let's just close this issue.
