### ISSUE TITLE
Qt strings are untranslated

### ISSUE THREAD

**Issue by glixx** [kaa-ching/tbe#42]
Buttons "Yes", "No" are untranslated.
![a5](https://cloud.githubusercontent.com/assets/2681872/10620786/a7bd56d8-7785-11e5-9de0-1b452d0214ec.png)

**Comment by glixx** [comment]
Context Menu is not translated too.
![a7](https://cloud.githubusercontent.com/assets/2681872/10621382/26dfd104-7789-11e5-9727-7afc14b87964.png)

**Comment by kaa-ching** [comment]
This should be a mistake in the Qt translator. Oh. Stupid me. The Qt translator doesn't work. Same cause as the previous translation bug. Duh.
