### ISSUE TITLE
description looks like url

### ISSUE THREAD

**Issue by glixx** [kaa-ching/tbe#43]
If prev. description was with url, then the next description looks like url:
![a6](https://cloud.githubusercontent.com/assets/2681872/10621352/ef5a0790-7788-11e5-8030-b1ca30cf1a29.png)

**Comment by kaa-ching** [comment]
Which sequence of levels is this? I can obviously only reproduce this if you tell me the english names, my Russian is rather rusty...

**Comment by glixx** [comment]
I don't know steps to reproduce. I see this issue not always.

**Comment by kaa-ching** [comment]
If this isn't it, I have no clue what to do...
Moving to Milestone B...

**Comment by kaa-ching** [comment]
I cannot find this issue anymore.
