### ISSUE TITLE
No picture for Cola+mint Bottle

### ISSUE THREAD

**Issue by glixx** [kaa-ching/tbe#44]
elce09/005.xml: no picture for "Cola+mint Bottle"

![a8](https://cloud.githubusercontent.com/assets/2681872/10621601/7d6f6b0a-778a-11e5-918d-8863160ef085.png)

**Comment by kaa-ching** [comment]
I'm pretty sure your tree is out-of-sync if this happens...
Will check tomorrow!

**Comment by glixx** [comment]
Pictures should be on the left side. Else if string is big, then no picture.

**Comment by kaa-ching** [comment]
It looks ugly if I align left, but it beats the alternative.

**Comment by kaa-ching** [comment]
Does this help?

**Comment by kaa-ching** [comment]
This is a regression from the fix for issue #41.

**Comment by glixx** [comment]
Text looks better, but issue is present for picture again.

**Comment by kaa-ching** [comment]
Is this better? :smiley: 
![toolbox-wrapped](https://cloud.githubusercontent.com/assets/4249656/10646669/a441757a-7834-11e5-99e9-fd620fb51fe6.png)

**Comment by glixx** [comment]
Yes, but I don't see this in ee03cda

**Comment by kaa-ching** [comment]
Relax, I'm trying to make it even better!

**Comment by kaa-ching** [comment]
And this is what I'm going to settle at. Let's hope no-one needs 5 lines...
![even-better](https://cloud.githubusercontent.com/assets/4249656/10648670/094b4bd4-7840-11e5-90b4-fb91ad407917.png)

**Comment by kaa-ching** [comment]
BTW, I just realized you translated as Coca-Cola.

**Comment by kaa-ching** [comment]
not for this release :stuck_out_tongue:
