### ISSUE TITLE
Release naming

### ISSUE THREAD

**Issue by glixx** [kaa-ching/tbe#46]
Sources should be "name-version" format. It was discussed for numeric packaging.
Look at example: https://github.com/viktor-zin/afce/releases

**Comment by glixx** [comment]
If to click "Source code (tar.gz)", then "tbe-0.9.2.1.tar.gz" should be generated.

**Comment by kaa-ching** [comment]
You're talking about the https://github.com/kaa-ching/tbe/releases page, clicking on the current milestone-A .tar.gz download link.

That will change as soon as the release binaries are published.

**Comment by kaa-ching** [comment]
Applied the patch you attached to the string change.
Created a new tag 'v0.9.2'. The tar.gz downloaded from github is now called `tbe-0.9.2.tar.gz`.

Note that the release is still in draft because I will be rebuilding the packages and verifying them.

**Comment by glixx** [comment]
I wrote 0.9.2.1 in spec. Why 0.9.2?

**Comment by kaa-ching** [comment]
Done, v.0.9.2.1 released.
