### ISSUE TITLE
Get download statistics

### ISSUE THREAD

**Issue by kaa-ching** [kaa-ching/tbe#52]
Apparently you need to do some scripting on the website for that...
http://stackoverflow.com/questions/4338358/github-can-i-see-the-number-of-downloads-for-a-repo

**Comment by kaa-ching** [comment]
Deliberately not assigning to a milestone, I'll leave it to DjSlash to accept his assignment and figure out when/how to do it.

**Comment by DjSlash** [comment]
From what I read this can't be done through gh-pages out of the box. So, it needs to be retreived either through some javascript or a secondary host (I could host it on my VPS).

**Comment by kaa-ching** [comment]
I don't mind the javascript.

I'm inclined to say that I would prefer running everything on github.io - so not on an external machine.
On the other hand: your machines are not a problem as the statistics don't need to be publicly available...

**Comment by DjSlash** [comment]
Oh, you don't want it on the site? Then just use&bookmark this: http://www.somsubhra.com/github-release-stats/

**Comment by kaa-ching** [comment]
I don't see the _need_ for it on-site.
But this is good info anyway :-)

For future reference, the full link is this:
 * http://www.somsubhra.com/github-release-stats/?username=kaa-ching&repository=tbe

No password needed.

**Comment by DjSlash** [comment]
I don't see the need either. But that was what I understood from your initial request. :)

Anyway, as the earlier mentioned url provides what you wanted, I'll leave it by that.
