### ISSUE TITLE
Fix DNS to contain CNAME's

### ISSUE THREAD

**Issue by kaa-ching** [kaa-ching/tbe#54]
@djslash wrote: 
> I'd rather see that the-butterfly-effect.org is CNAME'd to kaa-ching.github.io

Please write down what to tell to the hoster that handles http://www.the-butterfly-effect.org/, I'll tell the guy to look here and figure out what to do. He's good.

**Comment by DjSlash** [comment]
Currently both www.the-butterfly-effect.org and the-butterfly-effect.org have an `A` DNS-record. They should both be changed to a `CNAME` DNS-record that points to kaa-ching.github.io. Then Github will take care of pointing it to the repo's gh-pages. [Here's more info to read](https://help.github.com/articles/tips-for-configuring-a-cname-record-with-your-dns-provider/).

**Comment by kaa-ching** [comment]
I passed a link to this issue on to the hoster today.
