### ISSUE TITLE
Level goal text can be edited in-game

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#63]
The goal text for the level can be edited even in-game. If you are not careful, you can accidentally delete the description.
In that case, you would have to reload the level to make it visible again, but that's silly. :D

I use version 0.9.2.

**Comment by kaa-ching** [comment]
Agreed. I consider this a bug, actually.

**Comment by kaa-ching** [comment]
That commit closes this issue.

If all issues were as easy as this one :smiley:
