### ISSUE TITLE
Bouncing windows are annoying

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#64]
This is more a suggestion than a bug report, but it annoys me a lot:

The “bouncing” animation of opening and closing windows (e.g. goal text, post-it note, etc.) gets annoying over time. Especially it takes awkwardly long to finish (1-2 seconds, I guess).
Maybe it should just be disabled.
In case other players read this, do you agree?

I use 0.9.2.1.

**Comment by kaa-ching** [comment]
You are amazingly accurate in guessing how long the animation takes.
From src/view/animateddialog.cpp:
```
const qreal DURATION=1500;
    ...
theAnimation.setDuration(DURATION);
```
So it takes 1.5 seconds.

It should be possible to add a menu option (and a setting in the config file) to disable animations - or to halve the duration?

**Comment by Wuzzy2** [comment]
I'd argue to remove it entirely. What's the gain in having it in the first place, other than slowing down the player interactions? It decreases usability.
IMO the effect is not even visually pleasing to me after the 10th time. :D

**Comment by amarsman** [comment]
@Wuzzy2 Thanks for your valuable feedback. On which platform are you playing/testing and are you able to build the game yourself?

I agree with you comment about the "abuse" of animations but I'm sure there are other opinions also, making it configurable might be the best on the short term. But my opinion doesn't count here, I'm not really into playing games myself but like to help @kaa-ching. I only would play a game if it doesn't take too much of my time and TBE perfectly qualifies.

**Comment by kaa-ching** [comment]
Do @djslash and @lspacenl have opinions?

**Comment by Wuzzy2** [comment]
I am using GNU/Linux and I am able to build the game from the source code. So I could help testing. :-)

**Comment by kaa-ching** [comment]
Hi @Wuzzy2 if you can build from source, that's :+1: :+1: :+1: 

Can you please checkout the latest git and build it?
A few of the other tickets you mention are already solved :wink: 

Just a few package requirements: please take a look at https://github.com/kaa-ching/tbe/blob/master/INSTALLING.md and have fun watching it build!
I'm happy to have your comments!

**Comment by DjSlash** [comment]
I always have opinions! :wink:  In this case: I can't say it really annoys me, even after playing (with) this game after several years. It's part of the game and I grew to it. But it also doesn't pleases me and I can imagine that it bothers other players. I wouldn't be saddened if it got removed. Certainly wouldn't make it configurable, since it's just trivial.

**Comment by Rondom** [comment]
I have just tried this game for the first time and it bothered me a lot. The jumping animations are very distracting and (in my opinion) do not add anything to the game.
Honestly it reminded me of those horrible PowerPoint slides where the presenter was concentrating more on trying out all the different effects than the actual content.

**Comment by kaa-ching** [comment]
I've taken out the bounce and halved the animation time.
