### ISSUE TITLE
Poor goal descriptions in many levels

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#67]
Hi!
I think the descriptions/main instructions (non-Post-It) are often very terrible and useless. Apart from a poor grammar/language from time to time (e.g. things and animals are refered to as “he”/“she” instead of “it”), but let's ignore that for now.
Although I figured it out on my own sooner or later, I think it still is a bit annoying. As soon as TBE will have more difficult levels, the goal texts should be actually useful. Otherwise players get stuck for not even knowing what to do. xD

Sometimes you just don't know what the actual goal is. I don't think the actual goal texts should be moved into Post-it notes (which is what many levels seem to do). Also, it just makes the game appear very clunky.

I think the goals (and fail conditions) for almost all levels can safely be written in a very short sentence. Sometimes two sentences.

IMO the goal descriptions should:
* Be short and succinct
* Tell exactly what to do
* Tell what *not* to do (fail conditions)
* Leave out anything else

In one word: KISS (Keep It Simple and Stupid) xD

The “anything” else part could be moved into post-it notes. Especially hints and tutorial-like instructions.
As a player, I am not really interested in any “back-story” or something. ;)
Also, the actual goal should not be hidden in the (often) bla-bla text in the post-it note.
Many goal descriptions just pussyfoot around. :D

Some examples:
* Bouncing Balls: The goal just should say “Put the balls into the chest.” Yeah, the post-it part in the goal text could stay IMO since it is an early level.
* In Perfect Balance: Perfect example of bla-bla and no actual goal text. Just say something like “The butterfly must reach the flower alive.”.
* Extreme Tux Racer: I don't care from which game this level is inspired, but if you insist adding this information, you could move this bit into a post-it note. Also, not everyone may know that Tux is supposed to be the penguin, so maybe say just “the penguin” or “the penguin Tux”. (I have nothing against Extreme Tux Racer, by the way, I also played it).
* Jumping Around I: The goal text is totally missing the point (almost misleading), not a single word about that the *actual* goal is to put the pin into the chest.
* Loopings I, Cola Powered Bike, Domino Day are perfect examples of useless yadda-yadda without any real information
* There is even a level which just tells me “to figure it out by myself”. lol
* More levels, I won't list everything

PS: The text I written may sound very harsh, but actually I just want to make sure to have a basic level of “quality assurance”, especially if you are aiming for 1.0 release. :D

If you wish, I could rewrite the texts for you but I don't know how and if I saw correctly the level editor is currently broken, right? :-(

**Comment by kaa-ching** [comment]
I totally agree. The Descriptions are *not* for the back story - which is inconsistent at this point anyway.

On the technical point. I'd love if you can rewrite the descriptions.

All levels are in XML. The description is easy to find - at the top of the file.

Do you know how to use `git diff`? 
Or shall I ask @amarsman to teach you how to create pull requests?

**Comment by Wuzzy2** [comment]
Sure, I try to work on that. And I know how to use Git. :-)

**Comment by kaa-ching** [comment]
Sure, I try to work on that. And I know how to use Git. :-)
Sorry, my bad: I have no clue what your qualities are, yet. If you want, please drop me a few lines privately (email?) with real name, location, capabilities, past experience, education, expectations, etc.

**Comment by Wuzzy2** [comment]
Well, I choose not to disclose my private information. Also, I was already finished with the task before I got your message, so just I make the pull request instead of throwing my work away. ;-)
I just say I've been on GitHub for a while and made random contributions to a couple projects so far.
Otherwise I'd say you have to judge my work on the basis of … well … my work. xD

I also don't currently plan to become a long-term contributor to this project anyways.
