### ISSUE TITLE
Create difficult levels

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#68]
I think the game (version 0.9.2.1) was pretty easy so far. The 45 levels were not *bad*, just easy. (I was a seasoned player of TIM, and the Crazy Machines series, so it should not be surprising. :D). I think I finished them in a few hours or so.

It's not bad to have easy levels, but it's bad if its *just* easy levels.
There were a few levels in which I guess I have found a lame “shortcut” (probably I'll post issues for these later).
Many levels only have a few objects to insert, so there is not much you can do wrong. ;)

So maybe some more difficult levels should be created in the future.
I wish I could help, but it seems the level editor is currently broken. Can you give me a short message (maybe with an “@ mention”) when it works again?

**Comment by amarsman** [comment]
@kaa-ching: not sure how difficult it is to fix the level editor. Is it an option to build an older version and create levels to play with the current version? If so, which version?

**Comment by kaa-ching** [comment]
See issue #66 for things that are wrong with the level editor - apart from crashes, which are listed in issue #6 . If you know anything else, please add them to either ticket.

I've created the `levels/games/pingus-1.xml` level last weekend in 3 hours using a mix of a text editor, Inkscape (to do the new graphics) and the level creator. The level creator really needs some more love, but it does work if you know what you're doing. BTW: @lspacenl already found a few major shortcuts in that level, so I need to do more work on it...

**Comment by kaa-ching** [comment]
I'm going to close this issue, @Wuzzy2 has done amazing work :+1: :grinning:
