### ISSUE TITLE
Suggestion: No-build zone

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#69]
I don't know if it would be possible but it would be interesting to have a feature for zones in which you are not allowed to place any object. Those zones themselves do not collide with anything, so they are purely a new restruction.

I noticed some levels use a chain-link fence to block stuff to be placed but this solution falls flat if you can place small objects like a tennis ball. IIRC a tennis ball happily can fit into one of the “holes” of the chain-link fence. Example: “Bowlin pin plays soccer...” level.

**Comment by lspacenl** [comment]
the chickenwire fence in bowling pin plays soccer was resolved in e925ce55 . This will be part of the next (0.9.3) release.

**Comment by Wuzzy2** [comment]
I still managed to fit in a tennis ball into one of the “holes” in that level. It's harder to do, but still possible.

**Comment by kaa-ching** [comment]
Really? Wow!

**Comment by kaa-ching** [comment]
Done. Now I need to get back to work :-)
