### ISSUE TITLE
It's time to use Qt5

### ISSUE THREAD

**Issue by glixx** [kaa-ching/tbe#7]
Qt4 is not recommended for using (old, not very good support), the current is Qt5.
Changes should be minimal qt4->qt5.

**Comment by kaa-ching** [comment]
Qt4 is not end-of-lifed yet.
However, we want to move over before that happens.

**Comment by amarsman** [comment]
I don't think we will manage that, support ends on December 19 2015. I couldn't find anything about a further extension. Anyone already tried how big the effort might be for a port as a first step? Already an idea about potential problems with the used libraries?

See http://doc.qt.io/QtSupportedPlatforms/index.html and http://blog.qt.io/blog/2014/11/27/qt-4-8-x-support-to-be-extended-for-another-year/

**Comment by kaa-ching** [comment]
I don't have a clue yet.

**Comment by amarsman** [comment]
As building on Mac OS X 10.11 (El Capitan) doesn't work currently the priority of this task should be higher I think. See https://github.com/kaa-ching/tbe/wiki/MacOSXBuild

**Comment by kaa-ching** [comment]
For now, I've pushed my first commits on a separate branch.
Note that changes to two files are not committed yet - they need closer attention as things broke.

**Comment by kaa-ching** [comment]
What needs fixing:
 * [] except for the _Controls_ menu, none of the menu actions work - including _File>Quit_ .
 * [] scaling of decorators is failing (this is because ViewActionObjectDecorators uses a no longer supported member called `scale()`)
 * [] haven't checked i18n yet

**Comment by kaa-ching** [comment]
I've forgotten to reference this issue in quite a few commits. But things are really looking bright - should be done soon.
