### ISSUE TITLE
Dial B for Boom: Blue dominoes can be destroyed

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#70]
In the level “Dial B for Boom”, if you place the bowling ball just high enough above the blue dominoes and start the level and wait for the ball to hit the styrofoam, the dominoes just disappear? lolwut?
Also it's funny since you have a chance the bowling ball is able to “break through” and get to the balloon.

I use 0.9.2.1.

**Comment by kaa-ching** [comment]
That's a new one - I didn't know about that form of abuse yet. Thanks for the feedback!

BTW: indeed, the blue bricks disappear - they are balloons in a different shape :laughing:

**Comment by Wuzzy2** [comment]
Nope. I still can make the domioes make go “poof”. ;-)
I just need to place the bowling ball next to the post-it note, it still hits the styrofoam.

Tested in c152f9dcf8df69afc3cdadd493aaa45410469af1.
