### ISSUE TITLE
Simulation control buttons inconsistency after clicking into running simulation but not resetting

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#71]
To reproduce this, do this:

* Load *any* level
* Start the simulation by clicking on the “play” button
* Click anywhere on the simulation part of the window
* → A message appears asking you if you want to reset
* → Also the game has been automatically paused
* Say “No”

Now the game is still paused, but if you look at the simulation buttons (play/pause/fast-forward) you'll notice the “play” button is disabled but the pause and fast-forward buttons are enabled, although you are in pause mode now.

The same is true for fast-forward mode:
Repeat the same steps, but this time, go into fast-forward mode before clicking into the simulation part. Now the game is in pause mode again, but the pause and play buttons are enabled, and the fast-forward button is disabled.

I also noticed the status icon is also incorrect (does not show “pause”).

Seen in 0.9.2.1

**Comment by kaa-ching** [comment]
Really sharp observation!
I agree this is a bug. 
It is due to the game being brought in semi-pause, not updating the SimulationControls.
