### ISSUE TITLE
Can't toggle from “really fast-forward” to “fast forward” mode and vice-versa

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#72]
Two issues:

* [x] If you are in “really fast-forward” mode (Shift+f) you cannot go directly into “fast forward” mode (f) and vice-versa. You have to go into normal speed or pause mode first. This is a bit inconvenient.

* [x] I also noticed the icon is the same for both modes; I suggest to use a different icon for “really fast-forward” mode (three “arrows”).

Tested on ceadc7e6223ffd680e2c731bb51e7bddb6500267

**Comment by kaa-ching** [comment]
Wait, how did you learn about 'really fast forward' ?

I've updated your OP to contain two check boxes, as both issues need to be addressed separately.
The first requires adding a few state changes - that's easy.

The second one requires drawing and adding an image - simple as well if you know your way around Inkscape. Can you pick up the second part? Thanks.

**Comment by Wuzzy2** [comment]
I learned about “really fast forward” in the keyboard shortcuts dialog in 0.9.2.1. :P

I'm not an artist, but I think the icon seems easy enough for me. Okay, I'd try to adress part 2, but my Inkscape is currently broken. Hopefully I can fix it soon or I edit it another way.
