### ISSUE TITLE
Replay reset unavailable while in “really fast-forward” mode

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#74]
How to reproduce:

* Select any level
* Press [Shift]+[F] to enter “really fast forward” mode
* Try to reset the replay (1st button from the left, upper buttons)

It's not possible. The button for resetting the replay is disabled, also pressing [R] does not work. This button is available in “normal speed” and “fast-forward” and “pause” modes, so why not there?

Tested on: ceadc7e6223ffd680e2c731bb51e7bddb6500267 on GNU/Linux.

**Comment by kaa-ching** [comment]
This was deliberate when I designed it, but I agree it is not consistent.
