### ISSUE TITLE
Selecting a phone number closes phone number dialog

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#76]
If you select a phone number on the dynamite object, the dialog closes immediately.

This is counter-intuitive and IMO against basic UI design principles; a drop down list should not “do” something unless there is a very good reason to.
It is also a bad idea since this prevent you from scrolling through the options with the mouse wheel (it just closes after the first “scroll”.

Seen in ceadc7e6223ffd680e2c731bb51e7bddb6500267.

**Comment by kaa-ching** [comment]
I immediately fixed something else I noticed: the DetonatorBox contained two (empty) entries.

No longer :-)
