### ISSUE TITLE
Game can be tricked into “thinking” the level did not fail

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#77]
In ceadc7e6223ffd680e2c731bb51e7bddb6500267, I found a way to trick the game into “thinking” the level did not fail, although one of the fail conditions was met.

For testing, I chose the level “Spare the Balloon”. You fail this level if the balloon pops, which is easy. ;-)
Here's how to do it:
* Load the level “Spare the Balloon” freshly
* Start simulation and let the balloon pop
* → Fail dialog comes up
* Now either press R on the keyboard or click the reset button to the top right, NOT the one in the fail dialog!
* Now click on the “play” or “fast-forward” button on the top right
* → The fail dialog goes away
* Wait for the balloon to pop again

Tadaa! The fail dialog does NOT come up, and all future attempt in this level will also never fail again. You have to reload the level to have the fail dialog come up again.

Edit: I noticed the bug also applies for winning the level. If you do the steps above, but win instead, the victory condition will be ignored. as well on the 2nd run. But this time, you have to go into pause mode before the reset button becomes available.

**Comment by kaa-ching** [comment]
Thank you for reproducing this issue - I have observed it but never got my head wrapped around it.

Should be a relatively easy fix.

**Comment by kaa-ching** [comment]
Changeset 1303e55 removes the (not working anyway) hide/show code of simulations control.
It doesn't help this issue, but at least the code is cleaner. If this code *had* worked, that would have solved this issue. But alas: I don't believe in that solution. I'm going to have to make the sim controls "just work" - and thus reset the goals on reset.

**Comment by kaa-ching** [comment]
The reason for the problem is this code in `resizinggraphicsview.cpp`:
```
     // only need to display the dialog once...
     if (theWinFailDialogPtr!=nullptr)
	     return;
```

When you press 'r' and thus reset through the simcontrols, the WinFailDialogPtr doesn't get reset, it's just the window that's moved out...
