### ISSUE TITLE
Post-it note appears above other objects in some levels

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#79]
In some levels, the post-it note appears to be in front of other objects.

If a mobile object passes by in simulation mode, the post-it node is in front, rather than in the background (which I would expect).

Levels where I noticed it:
* Bouncing Balls
* Spare the Balloon
* Marble Boulevard
* Party at the office
* Poing Poing Poing

Tested in: ceadc7e6223ffd680e2c731bb51e7bddb6500267
OS: GNU/Linux

**Comment by kaa-ching** [comment]
I'm not sure if I consider this an issue or just a feature.

**Comment by Wuzzy2** [comment]
Maybe an easier way to fix this is to set the default `ZValue` of post-it notes to `1.0` or something (if this is possible), so it is in the background by default and most levels probably do not have to be checked manually.

**Comment by kaa-ching** [comment]
I think I've decided against this - PostIts remain on top. 
They're stuck "to the screen" and that's on top.

**Comment by Wuzzy2** [comment]
Well, we also have many levels where post-its are in the background. So we have a mix of background and foreground post-its.

Whatever, it's not *that* important anyways, haha.
