### ISSUE TITLE
Incorrect tooltip for egg and bird

### ISSUE THREAD

**Issue by glixx** [kaa-ching/tbe#8]
Tooltip for egg and bird is from ballon. It's strange to read about helium :)

**Comment by kaa-ching** [comment]
Ehhh, what level are you talking about?

**Comment by glixx** [comment]
Levels:
angry/birds1.xml
angry/birds2.xml

Bird and egg are based on ballon, but tooltip was not changed on new.

**Comment by kaa-ching** [comment]
git commit 39b9f3c ensures that a Description in a level file actually is used.
git commit 9f10efe adds tool tips for birds and eggs.

This closes this ticket
