### ISSUE TITLE
Hitting a butterfly is always a loss, regardless of level's fail conditions

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#83]
I have finally found my way around the editor and found some workarounds to make it more or less workable, whew. 

While creating levels, I noticed that the game considers it a loss whenever I hit a butterfly, regardless of the fail conditions. I am not sure if this is intended, but I want to note that this is surprising and may make levels impossible where the goal is to kill the butterflies, muhaha. xD
Or where you want to place butterflies, but you don't care about them (for goals, that is).

To reproduce, create a level with a butterfly in it, add some dummy goal and then place an object above the butterfly and start. The game should give you a “fail” message regardless of the fail conditions for this level.

PS: Expect a PR with my first TBE levels soon. :)

**Comment by kaa-ching** [comment]
Hardcoded game logic. Killing a butterfly is always a fail. That's a feature.

Killing a pingus is not a fail :wink:
