### ISSUE TITLE
Problem with the latest level

### ISSUE THREAD

**Issue by glixx** [kaa-ching/tbe#9]
If you will skip or finish the latest level, then tbe never run again.

**Comment by kaa-ching** [comment]
What I want to do, is create a new level that cannot be won.
It will contain a '[perpetuum mobile](https://en.wikipedia.org/wiki/Perpetuum_mobile)' and start running automatically.
It should be loaded when all levels are done.
Because it cannot be won or skipped, that resolves this issue.

**Comment by glixx** [comment]
Or to start from the first level if all were done. To delete config file after win in the latest level if all levels were done else return to level, which were not win.
Your algorithm will not work: if the latest level were done, but there is any skipped level in the list.

**Comment by kaa-ching** [comment]
I now have seen the issue myself.
When all levels have been played, TBE will fail on restart with the following message:

```
**** t=884: entry void MainWindow::loadLevelDelayed()
**** t=884: entry void MainWindow::loadLevel(const QString&)
***  t=884: Level::load("")
QFSFileEngine::open: No file name specified
**** t=884: *** CRITICAL ERROR: ERROR during reading file '': ' Cannot read file '''


**** t=886: Critical Popup - application will halt
```

**Comment by kaa-ching** [comment]
Resolved, closing issue.
