### ISSUE TITLE
Tool tip of milk cartons shows blue domino text

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#94]
The tool tip of the milk cartons (level “Ring the Bell”) shows the tool tip text for blue dominos.

Commit: 37077bff8dd172ddf6d2cd97199e0b799e4c90cd

**Comment by kaa-ching** [comment]
Yup, my bad.
I've put in a tool tip referring to a major US milk advertisement: https://en.wikipedia.org/wiki/Got_Milk%3F .

I hope that translators will recognize that and translate appropriately.
In dutch it would be e.g. "Melk is goed voor elk", "Melk de witte motor" or "Ik had nog zo gezegd: geen bommetje!"... http://www.thedailymilk.nl/de-10-meest-memorabele-melkreclames/
