### ISSUE TITLE
Bad collision polygon for ramps

### ISSUE THREAD

**Issue by Wuzzy2** [kaa-ching/tbe#99]
If you place a `LeftRamp` or `RightRamp` into the editor and start the simulation with “debug drawing” mode on, you notice the collision polygon for the ramps is pretty bad for the lower part which could be a problem if you want to use ramps for relocating balloons, for example.

Tested in 87d86c0bcc78928ffb602c024808da376f9f5bab.

**Comment by kaa-ching** [comment]
I'm happy you like the new feature in the level editor :smile:

**Comment by kaa-ching** [comment]
Let's actually also respond to the contents of this ticket.
The reason why the "collision polygon" is actually not matching the contour has to do with a bit of history. There are a few ramps in this game that wouldn't work if you make the contour fit better - they get too small for the physics engine.

However, the physics engine improved and we can also just find these ramps and implement them differently. So there's no excuse - we'd better fix them.

Actions:
 * [ ] find all ramps smaller than 0.4 width
 * [ ] adjust the contour code for ramps in `src/model/PolyObject.cpp`
 * [ ] test the above ramps for issues
 * [ ] adjust ramps (use wedges or so) if necessary
